version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Restaurant
    ports:
      - "3306:3306"
    volumes:
      - ./docker_data/mysql_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./docker_data/rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
