version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker_data/mysql_data:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d/:ro